/* eslint-disable @typescript-eslint/no-unused-vars */
export default {
AMOUNT_DATA_SOPURCE:"AMOUNT_DATA_SOPURC",
CARD_DATA:"CARD_DATA",

PLAYER_CARD:"PLAYER_CARD",
DEALER_CARD: "DEALER_CARD",
IS_GAMEOVER: "IS_GAMEOVER",
CARD_COUNT: "CARD_COUNT",
PLAYER_POINT:"PLAYER_POINT",
DEALER_POINT:"DEALER_POINT"
}
